### ISSUE TITLE
Can't do anything

### ISSUE THREAD

**Issue by 15JH** [Lattyware/manydecks#28]
1. I cannot sign up nor create any decks. There's no option to create a new deck and when I sign up with Google nothing happens.

## How to reproduce the bug
Steps to reproduce the behaviour:
1. Go to main page
2. Click sign up
3. Click sign up with Google

### Expected behaviour
I expected to be able to sign up and at that point be able to create a deck

**Comment by Lattyware** [comment]
This occurs due to blocking third party cookies, which you may have set in your browser or an extension.

You can either:
 - Sign in with Twitch instead.
 - Allow third party cookies for the Google sign-in.

Unfortunately this is due to how the google sign in is implemented, and not something we can fix our side.
