### ISSUE TITLE
Unable to upload a deck

### ISSUE THREAD

**Issue by sohotomi** [Lattyware/manydecks#3]
Every time I try to upload a deck at https://decks.md.rereadgames.com/ it comes up saying 

"Sorry, there appears to have been a problem, please try refreshing the page.

The server rejected that, please check for problems."

**Comment by Lattyware** [comment]
I transferred this as this is an issue with Many Decks rather than Massive Decks.

I just pushed a new version, can you try again and see if it works for you now? 

If it doesn't, it may be that there is an issue with parsing the deck you are uploading, if you could attach an example deck that you see the problem with, and I'll take a look.

**Comment by Lattyware** [comment]
I'll assume this is fixed now, please re-open or open a new issue if you encounter this problem again.
